version: '3.8'

services:
  listing-service:
    build: .
    ports:
      - "3003:3003"
    env_file:
      - .env
    # Allows container to reach other services exposed on your host machine
    extra_hosts:
      - "host.docker.internal:host-gateway"
