version: '3.8'

services:
  user-service:
    build: .
    ports:
      - "3002:3002"
    env_file:
      - .env
    # Allows container to reach other services exposed on your host machine
    extra_hosts:
      - "host.docker.internal:host-gateway"
